# Dimensions
ScreenWidth = 612
ScreenHeight = 612
TileSize = 36

# Game Settings
Fps = 1

# Colors (RGBA)
BackgroundColor = [31, 31, 31, 1] 

GridColor = [0, 3, 243, 1]

SnakeBodyColor = [188, 236, 185, 1]
SnakeHeadColor = [19, 255, 0, 1]
SnakeTailColor = [0, 150, 0, 255]

FoodColor= [242, 249, 25, 0.5]


